// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQ53TeHF3dJ2uzHf7fn9pxzwjMwcDaec',
    appId: '1:795562223858:web:1406eba9c7cccc8dd1886b',
    messagingSenderId: '795562223858',
    projectId: 'flutter-login-e3b4f',
    authDomain: 'flutter-login-e3b4f.firebaseapp.com',
    storageBucket: 'flutter-login-e3b4f.firebasestorage.app',
    measurementId: 'G-PNW802RLYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYU1jS5TF4jJnTfv3s2pON9_kvaxH_yU',
    appId: '1:795562223858:android:10fcd902ea89bc21d1886b',
    messagingSenderId: '795562223858',
    projectId: 'flutter-login-e3b4f',
    storageBucket: 'flutter-login-e3b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcoyvv5_S_kwqAb0EJ7e0dF9goggtNfJE',
    appId: '1:795562223858:ios:a939d57fd587402fd1886b',
    messagingSenderId: '795562223858',
    projectId: 'flutter-login-e3b4f',
    storageBucket: 'flutter-login-e3b4f.firebasestorage.app',
    iosBundleId: 'com.example.applicationCvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcoyvv5_S_kwqAb0EJ7e0dF9goggtNfJE',
    appId: '1:795562223858:ios:a939d57fd587402fd1886b',
    messagingSenderId: '795562223858',
    projectId: 'flutter-login-e3b4f',
    storageBucket: 'flutter-login-e3b4f.firebasestorage.app',
    iosBundleId: 'com.example.applicationCvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOQ53TeHF3dJ2uzHf7fn9pxzwjMwcDaec',
    appId: '1:795562223858:web:ce3a4262b90c761fd1886b',
    messagingSenderId: '795562223858',
    projectId: 'flutter-login-e3b4f',
    authDomain: 'flutter-login-e3b4f.firebaseapp.com',
    storageBucket: 'flutter-login-e3b4f.firebasestorage.app',
    measurementId: 'G-STHVY2X0JH',
  );
}
